SELECT f.FLAVOR
FROM FIRST_HALF f
LEFT JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) as JULY_TOTAL
    FROM JULY
    GROUP BY FLAVOR
) j ON f.FLAVOR = j.FLAVOR
ORDER BY (COALESCE(f.TOTAL_ORDER, 0) + COALESCE(j.JULY_TOTAL, 0)) DESC
LIMIT 3;