-- 코드를 작성해주세요
select YEAR(DIFFERENTIATION_DATE) as YEAR, (select max(SIZE_OF_COLONY) from ECOLI_DATA where YEAR(DIFFERENTIATION_DATE) = YEAR group by YEAR(DIFFERENTIATION_DATE)) - SIZE_OF_COLONY as YEAR_DEV, ID
from ECOLI_DATA
order by YEAR, YEAR_DEV